import '@styles/globals.css'
import React from 'react'

export const metadata = {
  title: 'This is the main layout',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout ({ children }: Props): React.ReactElement {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
